// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZQlc74mpqaVIMSKAXboolx6pMHlsz-bg',
    appId: '1:452375716864:web:f121c4f0a3282465dba4e5',
    messagingSenderId: '452375716864',
    projectId: 'ticktacktoe-282aa',
    authDomain: 'ticktacktoe-282aa.firebaseapp.com',
    databaseURL: 'https://your-project-id.firebaseio.com',
    storageBucket: 'ticktacktoe-282aa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArsGJ77gLjGsdV3rHjgSlJ1g0wiKzcK0M',
    appId: '1:452375716864:android:b9d1d93b9c3771e0dba4e5',
    messagingSenderId: '452375716864',
    projectId: 'ticktacktoe-282aa',
    storageBucket: 'ticktacktoe-282aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-GM-HN-dWOvKjXT7UtfNIAOfBM-2x2AM',
    appId: '1:452375716864:ios:1519e23bbb79b6c0dba4e5',
    messagingSenderId: '452375716864',
    projectId: 'ticktacktoe-282aa',
    storageBucket: 'ticktacktoe-282aa.firebasestorage.app',
    iosBundleId: 'com.example.tickTackToe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-GM-HN-dWOvKjXT7UtfNIAOfBM-2x2AM',
    appId: '1:452375716864:ios:1519e23bbb79b6c0dba4e5',
    messagingSenderId: '452375716864',
    projectId: 'ticktacktoe-282aa',
    storageBucket: 'ticktacktoe-282aa.firebasestorage.app',
    iosBundleId: 'com.example.tickTackToe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZQlc74mpqaVIMSKAXboolx6pMHlsz-bg',
    appId: '1:452375716864:web:1e4d255ee78750cbdba4e5',
    messagingSenderId: '452375716864',
    projectId: 'ticktacktoe-282aa',
    authDomain: 'ticktacktoe-282aa.firebaseapp.com',
    storageBucket: 'ticktacktoe-282aa.firebasestorage.app',
  );
}
